### ISSUE TITLE
Joern (new version) build fails

### ISSUE THREAD

**Issue by MrZhihao** [malteskoruppa/phpjoern#1]
Hi,
I'm trying to using phpjoern, but when I followed the step-"gradle build"(joern),something went wrong. The terminal always showed "build failed". Then I questioned StackOverflow and found the reason may be that the version of gradle isn't match. Hence, I hope to know what the version of gradle is or other measures to deal with this problem.
When executing that step, the error messages are as follows:
:projects:octopus:compileJava
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:35: error: ')' expected
                post("executeplugin/", (req, res) -> {
                                           ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:35: error: illegal start of expression
                post("executeplugin/", (req, res) -> {
                                                   ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:35: error: illegal start of expression
                post("executeplugin/", (req, res) -> {
                                                     ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:36: error: illegal start of type
                        return new ExecutePluginHandler().handle(req, res); });
                                                                             ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:38: error: invalid method declaration; return type required
                get("manageprojects/create/:projectName", (req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:38: error: illegal start of type
                get("manageprojects/create/:projectName", (req, res) -> {
                    ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:38: error: illegal start of type
                get("manageprojects/create/:projectName", (req, res) -> {
                                                          ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:38: error: ')' expected
                get("manageprojects/create/:projectName", (req, res) -> {
                                                           ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:38: error: ';' expected
                get("manageprojects/create/:projectName", (req, res) -> {
                                                              ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:38: error: <identifier> expected
                get("manageprojects/create/:projectName", (req, res) -> {
                                                                   ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:38: error: illegal start of type
                get("manageprojects/create/:projectName", (req, res) -> {
                                                                     ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:38: error: <identifier> expected
                get("manageprojects/create/:projectName", (req, res) -> {
                                                                      ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:38: error: ';' expected
                get("manageprojects/create/:projectName", (req, res) -> {
                                                                       ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:39: error: illegal start of type
                        return new CreateProjectHandler().handle(req, res);
                        ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:39: error: <identifier> expected
                        return new CreateProjectHandler().handle(req, res);
                              ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:39: error: ';' expected
                        return new CreateProjectHandler().handle(req, res);
                                  ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:39: error: illegal start of type
                        return new CreateProjectHandler().handle(req, res);
                                                       ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:39: error: <identifier> expected
                        return new CreateProjectHandler().handle(req, res);
                                                        ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:39: error: ';' expected
                        return new CreateProjectHandler().handle(req, res);
                                                         ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:39: error: invalid method declaration; return type required
                        return new CreateProjectHandler().handle(req, res);
                                                          ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:39: error: <identifier> expected
                        return new CreateProjectHandler().handle(req, res);
                                                                    ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:39: error: <identifier> expected
                        return new CreateProjectHandler().handle(req, res);
                                                                         ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:40: error: class, interface, or enum expected
                });
                 ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:42: error: class, interface, or enum expected
                get("manageprojects/delete/:projectName", (req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:44: error: class, interface, or enum expected
                });
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:46: error: class, interface, or enum expected
                get("manageprojects/list", (req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:48: error: class, interface, or enum expected
                });
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:50: error: class, interface, or enum expected
                get("database/importcsv/:projectName", (req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:52: error: class, interface, or enum expected
                });
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:54: error: class, interface, or enum expected
                get("database/importcsv/:projectName/:nodeFilename/:edgeFilename", (req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:56: error: class, interface, or enum expected
                });
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:58: error: class, interface, or enum expected
                get("database/importdgs/:projectName", (req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:60: error: class, interface, or enum expected
                });
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:62: error: class, interface, or enum expected
                get("database/importdgs/:projectName/:streamFilename", (req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:64: error: class, interface, or enum expected
                });
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:66: error: class, interface, or enum expected
                get("database/reset/:projectName", (req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:68: error: class, interface, or enum expected
                });
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:70: error: class, interface, or enum expected
                get("manageshells/list", (req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:72: error: class, interface, or enum expected
                });
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:74: error: class, interface, or enum expected
                get("manageshells/create/:projectName/:shellName", (req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:76: error: class, interface, or enum expected
                });
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:78: error: class, interface, or enum expected
                exception(RuntimeException.class, (e, req, res) -> {
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:78: error: <identifier> expected
                exception(RuntimeException.class, (e, req, res) -> {
                                                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:78: error: illegal start of type
                exception(RuntimeException.class, (e, req, res) -> {
                                                  ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:78: error: ';' expected
                exception(RuntimeException.class, (e, req, res) -> {
                                                              ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:81: error: illegal start of type
                });
                 ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/server/restServer/OctopusRestServer.java:85: error: class, interface, or enum expected
}
^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:11: error: illegal start of type
        default void beforeExecution() throws Exception {}
        ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:11: error: = expected
        default void beforeExecution() throws Exception {}
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:11: error: ';' expected
        default void beforeExecution() throws Exception {}
                    ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:11: error: illegal start of type
        default void beforeExecution() throws Exception {}
                                    ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:11: error: <identifier> expected
        default void beforeExecution() throws Exception {}
                                     ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:11: error: = expected
        default void beforeExecution() throws Exception {}
                                       ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:11: error: ';' expected
        default void beforeExecution() throws Exception {}
                                             ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:11: error: illegal start of type
        default void beforeExecution() throws Exception {}
                                                        ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:11: error: <identifier> expected
        default void beforeExecution() throws Exception {}
                                                         ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:13: error: = expected
        default void afterExecution() throws Exception {}
        ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:13: error: ';' expected
        default void afterExecution() throws Exception {}
               ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:13: error: <identifier> expected
        default void afterExecution() throws Exception {}
                                   ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:15: error: illegal start of type
        default Object result()
        ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:15: error: = expected
        default Object result()
                ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:15: error: ';' expected
        default Object result()
                      ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:15: error: illegal start of type
        default Object result()
                             ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:15: error: <identifier> expected
        default Object result()
                              ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:16: error: = expected
        {
        ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:16: error: ';' expected
        {
         ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:17: error: illegal start of type
                return null;
                       ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:17: error: <identifier> expected
                return null;
                           ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:18: error: = expected
        }
        ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:18: error: ';' expected
        }
         ^
/home/deo/joern/joern/projects/octopus/src/main/java/octopus/api/plugin/Plugin.java:19: error: reached end of file while parsing
}
 ^
71 errors
:projects:octopus:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':projects:octopus:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by malteskoruppa** [comment]
Hey. :smiley: 

Sorry, but this is not the correct place to post this issue. This GitHub project is phpjoern: It is a helper tool that takes a path to a file or a directory, searches for PHP files and generates the CSV input files needed as input for Joern. This helper tool is written in PHP, so there is nothing to compile here; PHP is an interpreted language. :wink: 

Judging from the output that you posted, what you tried to compile is the Octopus server. You don't really need it to do source code analysis for PHP, since Joern currently generates output files suitable for Neo4J when analysing PHP. Instead, you need to compile Joern in order to parse the CSV files output by this helper tool: Find Joern at https://github.com/octopus-platform/joern. If you want to compile the Octopus server nevertheless, please re-post this question in the appropriate GitHub project: https://github.com/octopus-platform/octopus

@fabsx00 You may be interested to take notice of this issue. :smiley:

**Comment by malteskoruppa** [comment]
Also, just a wild guess, but are you sure you are using Java 8 to compile the Octopus server or are you running some older version? Looking at the output above, it seems to me that your Java compiler may not know lambda expressions or default methods of interfaces, which would suggest you are running Java 7 or below.

**Comment by MrZhihao** [comment]
I feel sorry for inapproprate posting site, and then I'll post the same issue to Joern's Github page. But I don't think the cause of building failure is link to my Java version.  Java version in my virtual machine is oracle jdk1.7.0_u80 and 0.3.1 Joern can be successfully built up successfully. 😐
It will be nicer if u can response to me in joern's github page later and help me cope with it.😄
