### ISSUE TITLE
php-ast version 30 mismatching 

### ISSUE THREAD

**Issue by EdoardoVignati** [malteskoruppa/phpjoern#4]
Hi, could you please add in the installation step to checkout php-ast at version 0.1.4 (commit 701e853), otherwise it will fail the parsing step (version 30 not supported).
```
git clone https://github.com/nikic/php-ast
cd php-ast
git checkout 701e853
phpize
./configure
make
sudo make install
```

**Comment by malteskoruppa** [comment]
Thanks, done! :slightly_smiling_face:
